<?php
/** @package Laudo::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ExameMap.php");

/**
 * ExameDAO provides object-oriented access to the exame table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Laudo::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ExameDAO extends Phreezable
{
	/** @var int */
	public $CdExame;

	/** @var int */
	public $CdProcedimento;

	/** @var date */
	public $DtLancamento;

	/** @var int */
	public $CdMedico;

	/** @var int */
	public $CdMedicoSolicitante;

	/** @var int */
	public $FlLaudado;

	/** @var int */
	public $CdSituacaoExame;

	/** @var int */
	public $CdPaciente;

	/** @var string */
	public $NuProtocoloInterno;

	/** @var int */
	public $CdModalidade;

	/** @var int */
	public $CdLaudo;


	/**
	 * Returns the foreign object based on the value of CdLaudo
	 * @return Laudo
	 */
	public function GetCdLaudo()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_laudo_exame");
	}

	/**
	 * Returns the foreign object based on the value of CdMedico
	 * @return Medico
	 */
	public function GetCdMedico()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_medico_exame");
	}

	/**
	 * Returns the foreign object based on the value of CdMedicoSolicitante
	 * @return Medico
	 */
	public function GetCdSolicitanteMedico()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_medico_solicitante_exame");
	}

	/**
	 * Returns the foreign object based on the value of CdModalidade
	 * @return Modalidade
	 */
	public function GetCdModalidade()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_modalidade_exame");
	}

	/**
	 * Returns the foreign object based on the value of CdPaciente
	 * @return Paciente
	 */
	public function GetCdPaciente()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_paciente_exame");
	}

	/**
	 * Returns the foreign object based on the value of CdProcedimento
	 * @return Procedimento
	 */
	public function GetCdProcedimento()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_procedimento_exame");
	}

	/**
	 * Returns the foreign object based on the value of CdSituacaoExame
	 * @return SituacaoExame
	 */
	public function GetCdSituacaoExame()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_situacao_exame");
	}


}
?>