<?php
/** @package Laudo::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("LaudoMap.php");

/**
 * LaudoDAO provides object-oriented access to the laudo table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Laudo::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class LaudoDAO extends Phreezable
{
	/** @var int */
	public $CdLaudo;

	/** @var blob */
	public $BbLaudo;

	/** @var date */
	public $DtLaudo;

	/** @var int */
	public $CdMedico;

	/** @var blob */
	public $BbAssinado;

	/** @var timestamp */
	public $DtAssinado;

	/** @var date */
	public $DtRevisado;

	/** @var blob */
	public $BbLaudoRevisado;

	/** @var int */
	public $CdSituacaoLaudo;

	/** @var int */
	public $CdDigitador;

	/** @var int */
	public $FlAtivo;


	/**
	 * Returns a dataset of Exame objects with matching CdLaudo
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCdExames($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_laudo_exame", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of CdDigitador
	 * @return Digitador
	 */
	public function GetCdDigitador()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_digitador_laudo");
	}

	/**
	 * Returns the foreign object based on the value of CdSituacaoLaudo
	 * @return SituacaoLaudo
	 */
	public function GetCdSituacaoLaudo()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_situacao_laudo");
	}


}
?>