<?php
/** @package Laudo::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("MedicoMap.php");

/**
 * MedicoDAO provides object-oriented access to the medico table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Laudo::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class MedicoDAO extends Phreezable
{
	/** @var int */
	public $CdMedico;

	/** @var string */
	public $DsMedico;

	/** @var string */
	public $DsCrm;

	/** @var int */
	public $FlAtivo;

	/** @var blob */
	public $BbAssinatura;


	/**
	 * Returns a dataset of Exame objects with matching CdMedico
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCdExames($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_medico_exame", $criteria);
	}

	/**
	 * Returns a dataset of Exame objects with matching CdMedicoSolicitante
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCdSolicitanteExames($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_medico_solicitante_exame", $criteria);
	}


}
?>