<?php
/** @package Laudo::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ModalidadeMap.php");

/**
 * ModalidadeDAO provides object-oriented access to the modalidade table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Laudo::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ModalidadeDAO extends Phreezable
{
	/** @var int */
	public $CdModalidade;

	/** @var string */
	public $DsModalidade;

	/** @var int */
	public $FlAtivo;

	/** @var string */
	public $DsSigla;


	/**
	 * Returns a dataset of Exame objects with matching CdModalidade
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCdExames($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_modalidade_exame", $criteria);
	}


}
?>