<?php
/** @package Laudo::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PacienteMap.php");

/**
 * PacienteDAO provides object-oriented access to the paciente table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Laudo::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PacienteDAO extends Phreezable
{
	/** @var int */
	public $CdPaciente;

	/** @var string */
	public $DsPaciente;

	/** @var date */
	public $DtNascimento;

	/** @var char */
	public $DsSexo;

	/** @var string */
	public $DsObservacao;

	/** @var int */
	public $FlAtivo;


	/**
	 * Returns a dataset of Exame objects with matching CdPaciente
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCdExames($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_paciente_exame", $criteria);
	}


}
?>