<?php
/** @package Laudo::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ProcedimentoMap.php");

/**
 * ProcedimentoDAO provides object-oriented access to the procedimento table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Laudo::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ProcedimentoDAO extends Phreezable
{
	/** @var int */
	public $CdProcedimento;

	/** @var string */
	public $DsProcedimento;

	/** @var int */
	public $FlAtivo;

	/** @var int */
	public $CdModalidade;


	/**
	 * Returns a dataset of Exame objects with matching CdProcedimento
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCdExames($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_procedimento_exame", $criteria);
	}


}
?>