<?php
/** @package Laudo::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("SituacaoLaudoMap.php");

/**
 * SituacaoLaudoDAO provides object-oriented access to the situacao_laudo table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Laudo::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class SituacaoLaudoDAO extends Phreezable
{
	/** @var int */
	public $CdSituacaoLaudo;

	/** @var string */
	public $DsSituacaoLaudo;

	/** @var int */
	public $FlAtivo;


	/**
	 * Returns a dataset of Laudo objects with matching CdSituacaoLaudo
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCdLaudos($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_situacao_laudo", $criteria);
	}


}
?>